### ISSUE TITLE
NiTE download link dead

### ISSUE THREAD

**Issue by ranveeraggarwal** [totakke/homebrew-openni#16]
The NiTE link seems to be dead.

    > brew install nite
    ==> Installing nite from totakke/homebrew-openni
    ==> Downloading https://onedrive.live.com/download?resid=33B0FE678911B037%21573
    ==> Downloading from https://onedrive.live.com/pagenotfounderror
    
    curl: (22) The requested URL returned error: 404 Not Found
    Error: Failed to download resource "nite"
    Download failed: https://onedrive.live.com/pagenotfounderror

Is there a mirror, where I can procure it from?

**Comment by totakke** [comment]
404 error is a problem of redirection in homebrew. You can download the package from https://onedrive.live.com/download?resid=33B0FE678911B037%21573 directly.

Workaround:

```bash
$ wget 'https://onedrive.live.com/download?resid=33B0FE678911B037%21573' -O /tmp/nite.zip
$ brew edit nite
  url 'file:///tmp/nite.zip'
$ brew install nite
```

**Comment by ranveeraggarwal** [comment]
Yes, this works! Thank you :smile:

**Comment by vadivelselvaraj** [comment]
I tried `brew install nite` and I got the below. Any suggestions??
`MacBook-Pro-3:Formula vads$ brew install nite
Error: undefined method 'url' for Formulary::FormulaNamespacef53bd4d2eee21c824618a95d9c4c8a8c:Module
Please report this bug:
    https://git.io/brew-troubleshooting
/usr/local/Library/Formula/nite.rb:1:in 'load_formula'
/usr/local/Library/Homebrew/formulary.rb:23:in 'module_eval'
/usr/local/Library/Homebrew/formulary.rb:23:in 'load_formula'
/usr/local/Library/Homebrew/formulary.rb:36:in 'load_formula_from_path'
/usr/local/Library/Homebrew/formulary.rb:85:in 'load_file'
/usr/local/Library/Homebrew/formulary.rb:76:in 'klass'
/usr/local/Library/Homebrew/formulary.rb:72:in 'get_formula'
/usr/local/Library/Homebrew/formulary.rb:207:in 'factory'
/usr/local/Library/Homebrew/formulary.rb:352:in 'find_with_priority'
/usr/local/Library/Homebrew/extend/ARGV.rb:20:in 'block in formulae'
/usr/local/Library/Homebrew/extend/ARGV.rb:16:in 'map'
/usr/local/Library/Homebrew/extend/ARGV.rb:16:in 'formulae'
/usr/local/Library/Homebrew/cmd/install.rb:45:in 'install'
/usr/local/Library/brew.rb:85:in '<main>'
MacBook-Pro-3:Formula vads$`

**Comment by vadivelselvaraj** [comment]
Sorry, my nite.rb was empty. Did a retap on totakke/openni and it worked fine now with the updated url.
