### ISSUE TITLE
link seems to be dead

### ISSUE THREAD

**Issue by sdewailly** [totakke/homebrew-openni#17]
Hello,
I tried to install this repository but it fails! So as it was asked, I installed the JDK then it pass but there were a message asking to tap homebrew/science even if I made it before the 2 previous commands.

mbpdesebastien-1:~ sebastien$ brew install openni
==> Installing openni from homebrew/science
==> Installing dependencies for homebrew/science/openni: autoconf, automake, libtool, libusb, doxygen
==> Installing homebrew/science/openni dependency: autoconf
==> Downloading https://homebrew.bintray.com/bottles/autoconf-2.69.sierra.bottle.4.tar.gz
==> Downloading from https://akamai.bintray.com/a7/a76fca79a00f733c1c9f75600b906de4755dd3fbb595b1b55ded1347ac141607?__gda__=exp=1502648008~hmac=bd062a8f8d070c9b62d16936487688bd5b43d
######################################################################## 100,0%
==> Pouring autoconf-2.69.sierra.bottle.4.tar.gz
==> Caveats
Emacs Lisp files have been installed to:
  /usr/local/share/emacs/site-lisp/autoconf
==> Summary
🍺  /usr/local/Cellar/autoconf/2.69: 70 files, 3.0MB
==> Installing homebrew/science/openni dependency: automake
==> Downloading https://homebrew.bintray.com/bottles/automake-1.15.1.sierra.bottle.tar.gz
==> Downloading from https://akamai.bintray.com/d2/d2b27ce7782a966eb7c8570f7855c8c659bbefc97491a1fb54b66e7b58d26c63?__gda__=exp=1502648012~hmac=6b61aeea1f1caf6694d7a4186908e573edb1b
######################################################################## 100,0%
==> Pouring automake-1.15.1.sierra.bottle.tar.gz
🍺  /usr/local/Cellar/automake/1.15.1: 131 files, 3.0MB
==> Installing homebrew/science/openni dependency: libtool
==> Downloading https://homebrew.bintray.com/bottles/libtool-2.4.6_1.sierra.bottle.tar.gz
==> Downloading from https://akamai.bintray.com/78/78a1f6c6644eae01eb5c204ef705f7e48721a0fe8ece492c10c84791061885db?__gda__=exp=1502648015~hmac=bc7cf3f3ff04a3007a1464f03ad6970057fc7
######################################################################## 100,0%
==> Pouring libtool-2.4.6_1.sierra.bottle.tar.gz
==> Caveats
In order to prevent conflicts with Apple's own libtool we have prepended a "g"
so, you have instead: glibtool and glibtoolize.
==> Summary
🍺  /usr/local/Cellar/libtool/2.4.6_1: 70 files, 3.7MB
==> Installing homebrew/science/openni dependency: libusb
==> Downloading https://homebrew.bintray.com/bottles/libusb-1.0.21.sierra.bottle.tar.gz
######################################################################## 100,0%
==> Pouring libusb-1.0.21.sierra.bottle.tar.gz
🍺  /usr/local/Cellar/libusb/1.0.21: 29 files, 510.5KB
==> Installing homebrew/science/openni dependency: doxygen
==> Downloading https://homebrew.bintray.com/bottles/doxygen-1.8.13_1.sierra.bottle.1.tar.gz
==> Downloading from https://akamai.bintray.com/a5/a5e7436a64a38db42f85d8f48c683423288933d61e7607b82883388c73a8a724?__gda__=exp=1502648021~hmac=4b9fb2943c7b40329f0a23b9ab291612e7820
######################################################################## 100,0%
==> Pouring doxygen-1.8.13_1.sierra.bottle.1.tar.gz
🍺  /usr/local/Cellar/doxygen/1.8.13_1: 9 files, 13.1MB
==> Installing homebrew/science/openni
==> Downloading https://github.com/OpenNI/OpenNI/archive/Stable-1.5.7.10.tar.gz
==> Downloading from https://codeload.github.com/OpenNI/OpenNI/tar.gz/Stable-1.5.7.10
######################################################################## 100,0%
==> Downloading https://github.com/OpenNI/OpenNI/pull/92.diff
==> Downloading from https://patch-diff.githubusercontent.com/raw/OpenNI/OpenNI/pull/92.diff
######################################################################## 100,0%
==> Patching
==> Applying 92.diff
patching file Samples/NiViewer/glh/glh_convenience.h
==> ./RedistMaker
Last 15 lines from /Users/sebastien/Library/Logs/Homebrew/openni/01.RedistMaker:
make: *** Waiting for unfinished jobs....

*********************************
*   PrimeSense OpenNI Redist    *
*     2017-08-13 20:02:45       *
*********************************

Target: MacOSX
Version: 1.5.7.10
Num of compile jobs: 4

* Building OpenNI...
failed to execute: make  -j4 -C /private/tmp/openni-20170813-46884-4o9vk7/OpenNI-Stable-1.5.7.10/Platform/Linux/CreateRedist/../Build > /private/tmp/openni-20170813-46884-4o9vk7/OpenNI-Stable-1.5.7.10/Platform/Linux/CreateRedist/Output/BuildOpenNI.txt
Building Failed!

READ THIS: https://docs.brew.sh/Troubleshooting.html

Error: A newer Command Line Tools release is available.
Update them from Software Update in the App Store.

mbpdesebastien-1:~ sebastien$ brew install openni
==> Installing openni from homebrew/science
==> Downloading https://github.com/OpenNI/OpenNI/archive/Stable-1.5.7.10.tar.gz
Already downloaded: /Users/sebastien/Library/Caches/Homebrew/openni-1.5.7.10.tar.gz
==> Downloading https://github.com/OpenNI/OpenNI/pull/92.diff
Already downloaded: /Users/sebastien/Library/Caches/Homebrew/openni--patch-d2bc9bd628cc463b4e7cdc9bf3abc3ba78d04e4d451d02f7f6cf7d0c4d032634.diff
==> Patching
==> Applying 92.diff
patching file Samples/NiViewer/glh/glh_convenience.h
==> ./RedistMaker
==> /usr/local/Cellar/openni/1.5.7.10/bin/niReg /usr/local/Cellar/openni/1.5.7.10/lib/libnimMockNodes.dylib
==> /usr/local/Cellar/openni/1.5.7.10/bin/niReg /usr/local/Cellar/openni/1.5.7.10/lib/libnimCodecs.dylib
==> /usr/local/Cellar/openni/1.5.7.10/bin/niReg /usr/local/Cellar/openni/1.5.7.10/lib/libnimRecorder.dylib
🍺  /usr/local/Cellar/openni/1.5.7.10: 1,607 files, 28.0MB, built in 1 minute 20 seconds
mbpdesebastien-1:~ sebastien$ brew install sensor
==> Installing sensor from totakke/openni
==> Downloading https://github.com/PrimeSense/Sensor/archive/Stable-5.1.6.6.tar.gz
==> Downloading from https://codeload.github.com/PrimeSense/Sensor/tar.gz/Stable-5.1.6.6
######################################################################## 100,0%
==> ./RedistMaker
==> /usr/local/bin/niReg /usr/local/Cellar/sensor/5.1.6.6/lib/libXnDeviceSensorV2.dylib /usr/local/etc/primesense
==> /usr/local/bin/niReg /usr/local/Cellar/sensor/5.1.6.6/lib/libXnDeviceFile.dylib /usr/local/etc/primesense
==> Caveats
OpenNI formula is now provided by homebrew-science.
Tap homebrew-science in advance.
  `brew tap homebrew/science`
==> Summary
🍺  /usr/local/Cellar/sensor/5.1.6.6: 12 files, 1.1MB, built in 57 seconds
mbpdesebastien-1:~ sebastien$

Is it OK?

No problem with the sensor installation...

Then, it fails at NITE installation:
mbpdesebastien-1:~ sebastien$ brew install nite
==> Installing nite from totakke/openni
==> Downloading http://openni.ru/wp-content/uploads/2012/12/NITE-Bin-MacOSX-v1.5.2.21.tar.zip

curl: (7) Failed to connect to openni.ru port 80: Connection refused
Error: Failed to download resource "nite"
Download failed: http://openni.ru/wp-content/uploads/2012/12/NITE-Bin-MacOSX-v1.5.2.21.tar.zip

I notice in previous #16 issue that the link was changed, in order to work but as it is different than the one it is called in this version of the repository (the last), I prefer to ask before going further...

Can you help me out? Thanks in advance, Sébastien.

PS: Here is my config
mbpdesebastien-1:~ sebastien$ brew config
HOMEBREW_VERSION: 1.3.1
ORIGIN: https://github.com/Homebrew/brew
HEAD: 69799d97b1e7314912b2ee234dec2c179c5fb969
Last commit: 6 days ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 543d8e9b27b9bb25ce4491773684c30c8cb66dcc
Core tap last commit: 2 hours ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_REPOSITORY: /usr/local/Homebrew
HOMEBREW_CELLAR: /usr/local/Cellar
HOMEBREW_BOTTLE_DOMAIN: https://homebrew.bintray.com
CPU: quad-core 64-bit ivybridge
Homebrew Ruby: 2.0.0-p648
Clang: 8.1 build 802
Git: 2.11.0 => /Applications/Xcode.app/Contents/Developer/usr/bin/git
Perl: /usr/bin/perl
Python: /usr/bin/python
Ruby: /usr/bin/ruby => /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/bin/ruby
Java: 9
macOS: 10.12.6-x86_64
Xcode: 8.3.3
CLT: 8.3.0.0.1.1490382677
X11: N/A

**Comment by totakke** [comment]
> Is it OK?
>
> No problem with the sensor installation...

Probably yes.

> Then, it fails at NITE installation:
> mbpdesebastien-1:~ sebastien$ brew install nite
> ==> Installing nite from totakke/openni
> ==> Downloading http://openni.ru/wp-content/uploads/2012/12/NITE-Bin-MacOSX-v1.5.2.21.tar.zip
>
> curl: (7) Failed to connect to openni.ru port 80: Connection refused
> Error: Failed to download resource "nite"
> Download failed: http://openni.ru/wp-content/uploads/2012/12/NITE-Bin-MacOSX-v1.5.2.21.tar.zip

I succeeded in installing nite just now. The site may have been temporally downed, or your network may had a problem.

**Comment by sdewailly** [comment]
Hi Takeuchi,
It seems to work but now I want to start programming with these libraries...
Any advice welcome!
Bye, Sébastien

**Comment by sdewailly** [comment]
Hi Takeuchi,
I have good news, it works fine!

Meanwhile, after running the install commands there were a few warnings (please see the attached file). Hope it can help!

Bye, Sébastien

**Comment by totakke** [comment]
Thanks for the report, but those warnings do not matter. They are also printed on my environment.
